### ISSUE TITLE
Error when trying to list SG or ENI's

### ISSUE THREAD

**Issue by renato-mota** [cloud-crafts/sg-ripper#5]
Hello! I have been trying to use this project to help us clean our AWS Accounts, mainly to deal with the Orphan ENI problem. It seems very well built and useful, but when I tried to list our SG's, I got this error

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x8ce9dd]

goroutine 1121 [running]:
github.com/cloud-crafts/sg-ripper/pkg/core/clients.(*AwsEcsClient).buildCache(0xc000371860, {0xb57ab8, 0xf1aa20})
	/home/renato/ZeDefault/limpeza_recursos_vpc/sg-ripper/pkg/core/clients/ecsclient.go:90 +0x31d
github.com/cloud-crafts/sg-ripper/pkg/core/clients.(*AwsEcsClient).GetEcsAttachment(_, {_, _}, {0xc00039cb00, 0xc00032a9c0, 0xc0004b9b60, 0x0, 0xc0004b9b70, {0xc0004453b0, 0x1, ...}, ...})
	/home/renato/ZeDefault/limpeza_recursos_vpc/sg-ripper/pkg/core/clients/ecsclient.go:31 +0xd4
github.com/cloud-crafts/sg-ripper/pkg/core/builders.(*EniDetailsBuilder).getEcsAttachmentAsync(_, {_, _}, {0xc00039cb00, 0xc00032a9c0, 0xc0004b9b60, 0x0, 0xc0004b9b70, {0xc0004453b0, 0x1, ...}, ...}, ...)
	/home/renato/ZeDefault/limpeza_recursos_vpc/sg-ripper/pkg/core/builders/enidetailsbuilder.go:142 +0x78
created by github.com/cloud-crafts/sg-ripper/pkg/core/builders.(*EniDetailsBuilder).FromRemoteInterfaces in goroutine 1
	/home/renato/ZeDefault/limpeza_recursos_vpc/sg-ripper/pkg/core/builders/enidetailsbuilder.go:53 +0x89b

```

Is there some kind of limit on how many resources we can have in our accounts?

`go run main.go list -n
`
This is the command I tried. When I pass the list of SGs to be listed, it works fine

Thanks in advance!

**Comment by Ernyoke** [comment]
Hi @renato-mota,

Thank you for reporting this issue. 
AWS usually imposes limits on the number of each resources, but in case of `sg-ripper` we do not really have to deal with this limits, since we try to list everything.

Can you please clarify what you mean by an orphan ENI?
